# Some Experiments in Correlation and Sorting Matrices

In [2]:
import numpy as np

# Generate a random matrix for demonstration
np.random.seed(0)
matrix = np.random.rand(5, 5)

# Calculate the correlation matrix
correlation_matrix = np.corrcoef(matrix)
print(correlation_matrix)

# Get the dimensions of the matrix
n_rows, n_columns = matrix.shape

# Initialize variables to keep track of the highest correlation values and their indices
max_corr = 0
max_row = -1
max_col = -1

# Loop through the upper triangle of the correlation matrix to find the highest correlation
for row in range(n_rows):
    for col in range(row + 1, n_columns):
        corr = correlation_matrix[row, col]
        if abs(corr) > abs(max_corr):
            max_corr = corr
            max_row = row
            max_col = col

# Print the result
print(f"Highest correlation is between row {max_row} and column {max_col}: {max_corr}")

[[ 1.          0.07728112  0.38783087 -0.61705212  0.57560937]
 [ 0.07728112  1.          0.73848658  0.38617619  0.29781032]
 [ 0.38783087  0.73848658  1.         -0.28594208  0.85471571]
 [-0.61705212  0.38617619 -0.28594208  1.         -0.73990471]
 [ 0.57560937  0.29781032  0.85471571 -0.73990471  1.        ]]
Highest correlation is between row 2 and column 4: 0.8547157051041867


In [4]:
if "np" not in globals():
    import numpy as np

# Generate a random matrix for demonstration
np.random.seed(0)
matrix = np.random.rand(5, 5)

# Calculate the correlation matrix
correlation_matrix = np.corrcoef(matrix)
print(correlation_matrix)


# Get the dimensions of the matrix
n_rows, n_columns = matrix.shape

# Initialize a list to store correlation values and their corresponding indices
correlation_list = []

# Loop through the upper triangle of the correlation matrix to find and store correlations
for row in range(n_rows):
    for col in range(row + 1, n_columns):
        corr = correlation_matrix[row, col]
        correlation_list.append((row, col, corr))

# Sort the list in descending order of correlation values
correlation_list.sort(key=lambda x: abs(x[2]), reverse=True)

# Print the sorted list
for i, (row, col, corr) in enumerate(correlation_list):
    print(f"#{i + 1}: Row {row} and Column {col} - Correlation: {corr}")

[[ 1.          0.07728112  0.38783087 -0.61705212  0.57560937]
 [ 0.07728112  1.          0.73848658  0.38617619  0.29781032]
 [ 0.38783087  0.73848658  1.         -0.28594208  0.85471571]
 [-0.61705212  0.38617619 -0.28594208  1.         -0.73990471]
 [ 0.57560937  0.29781032  0.85471571 -0.73990471  1.        ]]
#1: Row 2 and Column 4 - Correlation: 0.8547157051041867
#2: Row 3 and Column 4 - Correlation: -0.739904711857788
#3: Row 1 and Column 2 - Correlation: 0.7384865841088747
#4: Row 0 and Column 3 - Correlation: -0.6170521204286958
#5: Row 0 and Column 4 - Correlation: 0.5756093686930877
#6: Row 0 and Column 2 - Correlation: 0.3878308748907127
#7: Row 1 and Column 3 - Correlation: 0.3861761863648693
#8: Row 1 and Column 4 - Correlation: 0.29781031915286
#9: Row 2 and Column 3 - Correlation: -0.2859420769068527
#10: Row 0 and Column 1 - Correlation: 0.07728111752883252
